spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://localhost:8081
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stocks/**
  discovery:
    client:
      registration:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
