spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081 # lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:8082 # lb://order-service
          predicates:
            - Path=/orders/**
        - id: stock-service
          uri:  http://localhost:8083 # lb://stock-service
          predicates:
            - Path=/stocks/**
  discovery:
    client:
      registration:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
