spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081 # lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://order-service:8082 # lb://order-service
          predicates:
            - Path=/orders/**
        - id: stock-service
          uri:  http://stock-service:8083 # lb://stock-service
          predicates:
            - Path=/stocks/**
  discovery:
    client:
      registration:
        enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
     defaultZone: http://eureka-server:8761/eureka/
