spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcay51/config-repo
          searchPaths: '{application}'
eureka:
  client:
    service-url:
     defaultZone: http://eureka-server:8761/eureka/