spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mcay51/config-repo
          searchPaths: '{application}'
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
     defaultZone: http://eureka-server:8761/eureka/