server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    initialization-mode: always
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true # Konsolda SQL sorgularını görmek için
    hibernate:
        ddl-auto: update # create, create-drop, validate, none veya update olabilir
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
eureka:
  client:
    service-url:
     defaultZone: http://eureka-server:8761/eureka/