server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microcommerce
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 1000ms
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5000ms
        failureRateThreshold: 50      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
