server:
  port: 8083

spring:
  application:
    name: stock-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microcommerce
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/