server:
  port: 8083

spring:
  application:
    name: stock-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microcommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, none veya update olabilir
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Konsolda SQL sorgularını görmek için
    format-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 1000ms
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5000ms
        failureRateThreshold: 50 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/